FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive LANG=en_US.UTF-8

RUN apt update 
RUN apt install -y build-essential
RUN apt install -y gcc
RUN apt install -y g++
RUN apt install -y gcc-multilib
RUN apt install -y make
RUN apt install -y cmake
RUN apt install -y openssl
RUN apt install -y vim
RUN apt install -y nano